Repository EUREKA-ITB/eureka-itb24, pull requests merged in 2024-05, with the labels that each got.

#8 style: switch primary font to barlow
  src/lib/fonts.ts
Labels: enhancement

#22 chore: update next version to 14.2.3
  package-lock.json
  package.json
Labels: Dependencies

#6 [CU-86epa7zd0] add: prettier action on pull request to master
  .github/workflows/prettier-action.yaml
  package-lock.json
  package.json
Labels: Settings

#7 [CU-86epa7zjm] add: color pallete from figma
  src/app/globals.css
  tailwind.config.ts
Labels: Settings

#23 chore: set build output to export
  next.config.mjs
Labels: Settings

#25 fix: boilerplate settings fixed
  next.config.mjs
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/navbar.tsx
  src/components/onboarding.tsx
  src/components/ui/button.tsx
Labels: Bug

#26 feat: main page footer
  package-lock.json
  package.json
  public/logo_eureka.svg
  src/app/page.tsx
  src/components/footer.tsx
Labels: Feature

#27 feat: coming soon page
  package-lock.json
  package.json
  public/DSC02956.png
  public/DSC03070.jpg
  public/DSC_0030.png
  public/DSC_0192.png
  public/IMG_0009.png
  public/IMG_0151.png
  public/line_blue.png
  public/line_yellow.png
  public/stars.png
  src/app/layout.tsx
  src/app/page.tsx
  src/components/coming-soon-gallery.tsx
  src/components/coming-soon-hero.tsx
  src/components/coming-soon-multiline.tsx
  src/components/coming-soon-previously.tsx
  src/components/coming-soon-socials.tsx
  src/components/theme-provider.tsx
  tailwind.config.ts
Labels: Feature

#28 feat: competition list
  public/img_phyOlympiad.svg
  public/img_sciWriting.svg
  src/components/competition-item.tsx
  src/components/competition.tsx
Labels: Feature
